### ISSUE TITLE
Unable to reproduce CodeT5 results

### ISSUE THREAD

**Issue by Veronicium** [wasiahmad/AVATAR#10]
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/29749047/192165967-bf54793f-5d9e-484e-a26e-f1db9360d70b.png">

Hi, I was trying to finetune CodeT5 for java-python translation but cannot reproduce the results. I got BLEU 63.77 / EM 1.88, which is much lower than your reported results: BLEU 67.0 / EM 2.8. The hyper-params are:

TRAIN_BATCH_SIZE=2
GRAD_ACCUM_STEP=16
LR=5e-5
NUM_TRAIN_EPOCHS=20
tokenizer_path=codet5/bpe;
source_length=510
target_length=510
--do_eval_bleu

All other hyper-params are as default in https://github.com/wasiahmad/AVATAR/blob/main/codet5/run.sh 

Could you give me some suggestions on how to reproduce your results? Thank you!

**Comment by wasiahmad** [comment]
There is no secret trick. So, I guess if you are unable to reproduce the result, please run 3-5 times for different seeds and see if you observe fluctuations in the result. Also, consider training for longer, in case if that helps.
