### ISSUE TITLE
How did you select the samples in g4g-functions?

### ISSUE THREAD

**Issue by Veronicium** [wasiahmad/AVATAR#11]
Hi! Sorry to bother you again. I found that there are 5132 geeksforgeeks samples in the whole AVATAR dataset, but only 3411 samples in g4g_functions. How did you select these 3411 samples? Did you filter out the problems in TransCoder-Eval?

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/29749047/193471367-06bf6d57-dde1-4520-ab12-399307ac679e.png">

Thank you!

**Comment by wasiahmad** [comment]
Your answer is in this script - https://github.com/wasiahmad/AVATAR/blob/main/data/g4g_fn.py

**Comment by Veronicium** [comment]
> Your answer is in this script - https://github.com/wasiahmad/AVATAR/blob/main/data/g4g_fn.py

I run this script by myself, and the length of "results" is only 2897, not 3411. I also compared the python functions in data/g4g_functions/train.java-python.python and data/transcoder_test_gfg/test.java-python.python. It seems that there are 283 overlapping code pieces:
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/29749047/193487664-4053ff0d-c27e-482c-8808-7b89cb78ad32.png">

Could you double-check the result of this script? Thank you!
