### ISSUE TITLE
 Issue Accessing Test Cases for Avatar Dataset

### ISSUE THREAD

**Issue by yz-qiang** [wasiahmad/AVATAR#15]
Hello,

I am currently using the avatar dataset to verify the effectiveness of my model in code translation. I obtained the Python-Java data pairs from `data/test.jsonl`. Now, I need the test cases for this data. To do this, I executed `bash download.sh` in the .test/cases directory.

However, I found that I am unable to access: https://docs.google.com/uc?export=download&id=1cg4EChbh2_hf-kMKX5g5qmz1HcWa-zSg. Could you please let me know if this website has been taken down or if there is another issue?

Thank you.

**Comment by initialWu** [comment]
I get the same issue. I'd like to know if you've solved this problem, and I'd be very grateful if you could give me a reply.

**Comment by wasiahmad** [comment]
You can download the test cases from https://drive.google.com/file/d/1AInTHzaZqym7WsT1B7yc8nZy7dA3ovPf/view?usp=drive_link.
