### ISSUE TITLE
Could you please help provide the trained model parameters?

### ISSUE THREAD

**Issue by zxniubihhh** [wasiahmad/AVATAR#2]
Hi @wasiahmad , I wonder if it’s possible for you to share the trained models?Since l am in urgent need of evaluating the experimental effects of these models on datasets (such as AVATAR and G4G), including assigned
specific codes after translation, but my GPU is in short supply. Thank you in advance!

**Comment by wasiahmad** [comment]
There are many models tested in different settings for the two datasets, therefore, it is not possible to upload them. We do not plan to share the fine-tuned models in the near future.
