### ISSUE TITLE
Typo Bug: Undefined 'tag' in DFG_java and DFG_csharp

### ISSUE THREAD

**Issue by ziwenyd** [wasiahmad/AVATAR#8]
https://github.com/wasiahmad/AVATAR/blob/bc9257091eb5125376eec6fb305faac1b71f9f5c/evaluation/CodeBLEU/parser/DFG.py#L254

Hi, I am working on a project that makes uses of your DFG_java code in the linked file, I found that there is a 'referenced before defined' error in this code. There should be another line define `tag=False` after `flag=False`.

I also found that other versions of DFG_java in this repository has the tag=False line defined, so I think this is just a typo.
(Also, I didn't make use of DFG_csharp but the DFG_csharp in this file `evaluation/CodeBLEU/parser/DFG.py` seem to be missing the tag initialization as well.)

Thanks for the good work!

Best

**Comment by wasiahmad** [comment]
Thank you, we have noted.
