### ISSUE TITLE
download error of the pretrained ckpts you shared

### ISSUE THREAD

**Issue by Veronicium** [wasiahmad/AVATAR#9]
Hi! I was trying to download the pretrained CodeT5-base and PLBART models by running download.sh, but I got the `awk: fatal: cannot open file './cookie' for reading (No such file or directory)` error. 
I also tried to directly open the download link in my web browser but it shows "404 file not found". Are you using the same pretrained model as in huggingface (i.e., `Salesforce/codet5-base`)?

Also, will you release the finetuned ckpts of those models? 

Thank you!

**Comment by wasiahmad** [comment]
PLBART checkpoint is there but the CodeT5-base model is not available in the link. Yes, we use the same model from HF.

No, we do not plan to release the fine-tuned checkpoints of the models anytime soon.
